version: '3.4'

networks:
  abelord:
    external:
      name: abelord.localhost

services:
  postgres:
    image: postgis/postgis:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    networks:
      default:
      abelord:
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  pgadmin-compose:
    image: dpage/pgadmin4
    networks:
      default:
      abelord:
    environment: 
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports: 
        - "16543:80"
    depends_on: 
        - postgres 

volumes:
  postgres-data:

